"""Validate the OpenAPI schema generated by the PWBS FastAPI app (TASK-193).

Usage:
    python scripts/validate_openapi.py

Returns exit code 0 if valid, 1 if invalid.
"""

from __future__ import annotations

import os
import sys

os.environ.setdefault("JWT_SECRET_KEY", "dev-only-placeholder-key-32chars!")
os.environ.setdefault("ENCRYPTION_MASTER_KEY", "dGVzdC1lbmNyeXB0aW9uLWtleS0zMg==")
os.environ.setdefault("DATABASE_URL", "postgresql+asyncpg://x:x@localhost/x")
os.environ.setdefault("DEBUG", "1")


def main() -> int:
    from pwbs.api.main import create_app

    app = create_app()
    schema = app.openapi()

    errors: list[str] = []
    paths = schema.get("paths", {})
    total_ops = 0

    for path, methods in sorted(paths.items()):
        for method, op in methods.items():
            total_ops += 1
            op_id = f"{method.upper()} {path}"

            if not op.get("summary"):
                errors.append(f"{op_id}: missing summary")
            if not op.get("description"):
                errors.append(f"{op_id}: missing description")
            if not op.get("responses"):
                errors.append(f"{op_id}: missing responses")

    # Validate schema structure
    required_keys = {"openapi", "info", "paths"}
    missing = required_keys - set(schema.keys())
    if missing:
        errors.append(f"Missing top-level keys: {missing}")

    info = schema.get("info", {})
    if not info.get("title"):
        errors.append("Missing info.title")
    if not info.get("version"):
        errors.append("Missing info.version")

    if errors:
        print(f"FAIL: {len(errors)} issue(s) in OpenAPI schema:")
        for e in errors:
            print(f"  - {e}")
        return 1

    print(f"OK: OpenAPI schema valid ({total_ops} operations across {len(paths)} paths)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
