"""Reminder ORM model (TASK-131).

Stores active reminders generated by the follow-up detection and
trigger engine. Each reminder links to a user, optionally to a source
document, and carries a status lifecycle: pending -> acknowledged | dismissed.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from pwbs.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class Reminder(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """An active reminder generated by the trigger engine."""

    __tablename__ = "reminders"
    __table_args__ = (
        Index("idx_reminders_user_status", "user_id", "status"),
        Index("idx_reminders_user_due", "user_id", "due_at"),
        Index("idx_reminders_source_doc", "source_document_id"),
    )

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Reminder type: follow_up, inactive_topic, open_question
    reminder_type: Mapped[str] = mapped_column(Text, nullable=False)

    # Human-readable summary of the reminder
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, server_default="")

    # Status lifecycle: pending -> acknowledged | dismissed | snoozed
    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="pending"
    )

    # Urgency: high, medium, low
    urgency: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="medium"
    )

    # When the reminder is due (for follow-ups: the deadline)
    due_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Who is responsible (extracted from follow-up commitment)
    responsible_person: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Structured metadata: original commitment text, entity refs, etc.
    reminder_metadata: Mapped[dict] = mapped_column(  # type: ignore[type-arg]
        "metadata", JSONB, nullable=False, server_default="{}"
    )

    # Optional link to the source document where the follow-up was detected
    source_document_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="SET NULL"),
        nullable=True,
    )

    # When the user acknowledged/dismissed this reminder
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # DSGVO: expiration
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    user: Mapped["User"] = relationship()  # noqa: F821
    source_document: Mapped["Document | None"] = relationship()  # noqa: F821